insert into competencia (descricao) values ('Fisioterapia'),
                                           ('Fonoaudiologia'),
                                           ('Nutrição'),
                                           ('Psicologia'),
                                           ('Terapia Ocupacional'),
                                           ('Enfermagem'),
                                           ('Medicina'),
                                           ('Odontologia'),
                                           ('Serviço Social'),
                                           ('Educação Física'),
                                           ('Farmácia'),
                                           ('Fisioterapia');