name: ci

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Teste com maven
        run: mvn clean test -Ptest
      - name: Build com maven
        run: mvn clean package -Pprod
      - name: Build the docker image
        run: docker build -t ogabrielsantoos/backend:service-empresas .
      - name: Log in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push no docker hub
        run: docker push ogabrielsantoos/backend:service-empresas
  deploy_instance_1:
    needs: build
    runs-on: [ self-hosted, empresas_1 ]
    steps:
      - name: Pull Docker image
        run: docker pull ogabrielsantoos/backend:service-empresas
      - name: Stop Docker Container
        run: docker stop empresas || true
      - name: Remover container
        run: docker rm empresas || true
      - name: Run Docker Container
        run: docker run --name empresas -d -p 8080:8080 ogabrielsantoos/backend:service-empresas
  deploy_instance_2:
    needs: build
    runs-on: [ self-hosted, empresas_2 ]
    steps:
      - name: Pull Docker image
        run: docker pull ogabrielsantoos/backend:service-empresas
      - name: Stop Docker Container
        run: docker stop empresas || true
      - name: Remover container
        run: docker rm empresas || true
      - name: Run Docker Container
        run: docker run --name empresas -d -p 8080:8080 ogabrielsantoos/backend:service-empresas