name: ci-cd

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: Build the docker image
        run: docker build -t ogabrielsantoos/backend:service-empresas .
      - name: Log in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push no docker hub
        run: docker push ogabrielsantoos/backend:service-empresas
